### ISSUE TITLE
LICENSE file rule shouldn't have required parameter that can be blank

### ISSUE THREAD

**Issue by ethomson** [stacklok/minder-rules-and-profiles#155]
The `license` rule has the following configuration:

```yaml
    properties:
      license_type:
        type: string
        description: |
          The license type to look for.
          For example, Apache, MIT, etc.
          Leave "" to only check for the presence of the license file.
    required:
      - license_filename
      - license_type
```

This field should not be required. Users should be able to omit the `license_type` and have it behave as if an empty string were specified.

This is especially important for programmatic parsing / understanding of this structure.
