### ISSUE TITLE
Populate the Severity for all rule types

### ISSUE THREAD

**Issue by rdimitrov** [stacklok/minder-rules-and-profiles#64]
The `Severity` field is missing in the existing rule types, so we should populate that.

**Tasks:** 
- [ ] Let's start with `medium` for all and we can discuss in the PR whether something needs higher or lower severity status.
- [ ] Add `alert` section for ruletypes that don't have it.
Example:
* Severity
```yaml
severity:
  value: critical
```
* Enabling alerts
```yaml
  # Defines the configuration for alerting on the rule
  alert:
    type: security_advisory
    security_advisory: {}
```
