### ISSUE TITLE
Trusty rule type should support rust and java

### ISSUE THREAD

**Issue by ethomson** [stacklok/minder-rules-and-profiles#67]
The Trusty PR rule type only supports npm, pypi, and go.

```
      ecosystems:
        - name: npm
          depfile: package-lock.json
        - name: pypi
          depfile: requirements.txt
        - name: go
          depfile: go.mod
```

We should support Java and Rust.
